### PR TITLE
remove extra files from npm, general cleanup, & improve requireability

### PR DESCRIPTION
**Pull request by slang800**
- remove trailing whitespace
- remove extra files from npm
- clean package.json with [fixpack](https://github.com/henrikjoreteg/fixpack)
- move `main` entrypoint into `./lib` - this allows us to require only parts of the library by doing a call like
`require('bencode/encode')`
- clean up code with [standard-format](https://github.com/maxogden/standard-format)
- remove `lib/dict.js` - it looks like it was the beginning of support for binary keys, but there
are no tests supporting it and (AFAIK) it's not doing anything useful. It seems like it a precursor to https://github.com/themasch/node-bencode/pull/27, but that PR died.

This is what the contents of the package looked like before:

```
├── AUTHORS
├── benchmark
│   ├── buffer-vs-string.js
│   ├── decode.js
│   ├── encode.js
│   ├── encoding-length.js
│   ├── instanceof.js
│   └── test.torrent
├── bencode.js
├── CHANGELOG.md
├── CONTRIBUTORS
├── dist
│   ├── bench.html
│   ├── bencode.js
│   ├── bncode.js
│   ├── tape.html
│   ├── tape.js
│   ├── test.html
│   ├── test.js
│   └── tests.js
├── flamegraph.html
├── isolate-0x2630e60-v8.log
├── lib
│   ├── decode.js
│   ├── decoder.js
│   ├── dict.js
│   └── encode.js
├── LICENSE.md
├── Makefile
├── package.json
├── README.md
└── test
    ├── abstract-encoding.test.js
    ├── a.js
    ├── data.js
    ├── decode.buffer.mocha-test.js
    ├── decode.buffer.test.js
    ├── decode.utf8.mocha-test.js
    ├── decode.utf8.test.js
    ├── encode.mocha-test.js
    ├── encode.test.js
    ├── lib.js
    ├── mocha.opts
    └── specifications.md
```

This is what the contents of the package look like now:

```
├── CHANGELOG.md
├── CONTRIBUTORS
├── lib
│   ├── decode.js
│   ├── encode.js
│   └── index.js
├── LICENSE.md
├── package.json
└── README.md
```

### CODE REVIEW

**Comment by themasch** [comment]
looks good for me but I'd like to hear @jhermsmeier's opinion on this, especially it removes the Dict-"feature". 
Since the tests still work, it doesn't really "change" the public api. :+1: from my side

**Comment by jhermsmeier** [comment]
This looks pretty good at first glance, I'll have to spend a few more minutes on this though, I think.
Especially because there was a reason for the binary keys support, and removing it just because we don't have any tests for it seems like we might be breaking someone's use of `bencode` by doing that.
I'd rather like to add tests for binary keys and keep the functionality.

**Comment by slang800** [comment]
@jhermsmeier - Cool, be sure to leave comments if you find anything. And right now `binarySet` is the only function that we're calling from `Dict`, and that just does `this[key] = value`, so we basically are just using it as a regular hash-map. Some other package might be using `Dict.binaryKeys`, so we could release `1.0.0` just to be safe, but I don't think there would be any reason to use it and it doesn't seem to be documented anywhere.

**Comment by slang800** [comment]
PS: turns out I was wrong about being able to do `require('bencode/encode')`... That doesn't work and I'd need to do `require('bencode/lib/encode')`. I could've sworn those requires resolved relative to `main`, but I can't find any docs on that having changed, so I guess we'd have to move the stuff out of `lib`, add in placeholders at the root dir like [readable-stream](https://github.com/nodejs/readable-stream) does, or move them up during a build step before publishing. :disappointed:

**Comment by jhermsmeier** [comment]
> so I guess we'd have to move the stuff out of lib

Yeah, I think we might leave that for another PR.

I've looked over it now, and from what I can see the binary key dict didn't really work and also not in a nice fashion – so removing that is cool.

Do you also want to add `standard` to `npm test`, so that we'll be forced to stick with it and it lints PRs etc.? Then this will be good to merge from my side – @themasch?

Just a note for future PRs: You might want to do things like changing code style formatting in a separate PR, as people might not be too fond of `standard` (I myself am not using it, for example), which could make separating the functionality related changes from the formatting a bit of a hassle ;)

**Comment by slang800** [comment]
> Do you also want to add standard to npm test

Sure, I'll add that in a sec

> You might want to do things like changing code style formatting in a separate PR, as people might not be too fond of standard

Yeah - I split stylistic changes into separate commits for that very reason... with an interactive rebase or simple cherrypicking you can select a subset of the changes and only merge those.

**Comment by jhermsmeier** [comment]
Thank you! Published as `0.10.0` now.

**Comment by slang800** [comment]
sweet, thanks!

**Comment by themasch** [comment]
:+1:

**Pull request merged**
