### PR TITLE
abstract-encoding compliant and other

### PR DESCRIPTION
**Pull request by fanatid**
Related: #37

Sorry, huge PR (and need major bump), maybe you will not agree with some thing, but I ready for discuss.

- [mafintosh/abstract-encoding](https://github.com/mafintosh/abstract-encoding) compliant
- [feross/standard](https://github.com/feross/standard/) codestyle
- [strict following by specification](http://www.bittorrent.org/beps/bep_0003.html)
- only strings, integers, list and dicts (float are not allowed - https://github.com/themasch/node-bencode/issues/14, boolean are not allowed -- https://github.com/themasch/node-bencode/issues/36 https://github.com/themasch/node-bencode/pull/38)

JavaScript doesn't support integers more than 2^53, it's bad, I don't know how resolve https://github.com/themasch/node-bencode/issues/35 because I do not want add `BigNumber` or something.

`encode` and especially `decode` is slower now, because `string` are used now not `Buffer`.

@feross @mafintosh @pldubouilh I'd be happy if you will participate in discussion to this PR.

### CODE REVIEW

**Comment by themasch** [comment]
Okay, this would be the second major rewrite of node-bencode and I really appreciate your effort to make this happen. 

I haven't got the time right now to do a full in-depth analysis of the changes but from what I see is that it totally changes the API (can't specifiy the encoding anymore), removes features we already discussed about (float conversion, booleans, bignums) and totally wrecks our performance (decode goes from 22kops/s down to 1.5kops/s and is slower than bncode). 

While I like some of the changes (e.g. code style, gitignore, corrected license file) I don't think its a good idea to totally change everything. 

A lot of packages are depending on [node-bencode](https://www.npmjs.com/browse/depended/bencode), while some of them might do it just because of the name, some of them might actually use what we've done in the past years. Semver to the rescue, they could still use the old version but that would imply that we have to support 2 major versions. One providing the old legacy API, one providing the new abstract-encoding-only api. 

So what It comes to is that bencode 1.0+ would be an entirely different project with different specs, different goals and a new codebase. Why not start an entirely new project then? Because of the name? 

I really need to hear some users & contributors opinions first.

**Comment by fanatid** [comment]
decoding performance is bad because my code return `string` always, for example if [dht_encode](https://github.com/stbuehler/nodejs-dht-bencode/blob/ad847b909737506216e596669967c5ee7646dc12/lib/bencode.js#L92) also will return strings speed will be same.

Not think that that supporting 2 major version is good decision. In this case I think will better start new project. But I not big fan of new projects, I don't see sense in creating new when you can improve old.

**Comment by fanatid** [comment]
replace string to buffer (except dictionary keys), new benchmark result: https://github.com/fanatid/node-bencode/tree/36067506e99716dcc738f9ba7091551cc6e98ed2#benchmark

**Comment by fanatid** [comment]
published as [bencode.js](https://www.npmjs.com/package/bencode.js)

**Pull request closed without merging**
