### PR TITLE
rm safe-buffer

### PR DESCRIPTION
**Pull request by jimmywarting**
part of https://github.com/brave/brave-browser/issues/5490

(Always require latest Buffer module)

### CODE REVIEW

**Comment by themasch** [comment]
Thanks a lot for the pull requests, getting rid of a dependency sounds great! 

I am out of the loop with node, what nodejs version do we require for safe-buffer to be not helpful anymore? Do we need a new major release with a new minimum node version requirement to support this? 
Also, seems like travis is finally defunct for this repo, I guess someone need to move that to github actions...

**Comment by jimmywarting** [comment]
> what nodejs version do we require for safe-buffer to be not helpful anymore?

I asked this question also a while back... https://github.com/feross/safe-buffer/issues/24 when you only support v6+ then you don't need it

>  I guess someone need to move that to github actions...
👍

**Comment by jimmywarting** [comment]
if you like perhaps switch to a ESM only package.

**Comment by themasch** [comment]
I just merged that adds github actions for running test. Could you please merge those changes in this branch. I ran the test locally with node12, and do not expect any breakage, but just to be safe...here

 > I asked this question also a while back... feross/safe-buffer#24 when you only support v6+ then you don't need it

okay, thats a long time ago...

**Comment by jimmywarting** [comment]
> Could you please merge those changes in this branch

I did, didn't happen so much new stuff...

**Pull request merged**
