### PR TITLE
Add support for large integers

### LINKED ISSUE #35: MAX_INT64 issue
[According to the bep_0044](http://bittorrent.org/beps/bep_0044.html), it should be possible to set an integer to MAX_INT64, (i.e. 0x7fffffffffffffff). [libtorrent successfully bencode this number](https://github.com/arvidn/libtorrent/blob/master/test/test_bencoding.cpp#L242), although node-bencode doesn't allow this and I receive this error :

```javascript
WARNING: Possible data corruption detected with value 9223372036854776000: Bencoding only defines support for integers, value was converted to 0
```

Which is fairly normal as my number is too big.

At the moment I hacked the number encoding case to push a hand crafted buffer when I detect an overflow, but it's not pretty at all... I don't see any easy solution, apart from using a library dedicated to handling large numbers, like [node-int64](https://github.com/broofa/node-int64).

Any thoughts ?
Cheers !

### PR DESCRIPTION
**Pull request by jhermsmeier**
**[WIP]:** Adds support for large `2^53+` integers via [`bignumber.js`](https://github.com/MikeMcl/bignumber.js) as proposed in #35.
Not sure this is the best way of doing it – been thinking about a way to hook certain types or define custom ones, similiar to the mechanic `msgpack` uses – which I'll attempt to explore as well.

Closes #35

### CODE REVIEW

**Comment by fanatid** [comment]
Why not use [indutny/bn.js](https://github.com/indutny/bn.js)?

**Comment by jhermsmeier** [comment]
> Why not use indutny/bn.js?

I might, after I have explored what else I had in mind, and once I get to the benchmarks on this one, if this one happens. With a type hook system this won't even be necessary, because people would be able to choose their own way of parsing types, if need be.

**Comment by jhermsmeier** [comment]
So... it's been a while, but I got around to trying out that idea I had, which is basically a middleware-style way of adding support for other types, i.e.:

```js
var assert = require('assert')
var Bencode = require('./index')
var BigNumber = require('bignumber.js')
// OR var BigNumber = require('bn.js')

// The current API still works as before,
// but can't have any new types added to it globally,
// to avoid trashing other things using it (in deduplicated bundles, for example)
Bencode.encode({ something: 'with a value' })
Bencode.decode( buffer )

// Create a new instance of Bencode (which uses it's own set of encoder/decoder),
var bignumBencode = new Bencode()

// Register a type check, encode & decode function for a new type
bignumBencode.use('bignumber', 'number', {
  check: function (value) { return value instanceof BigNumber },
  encode: function (buffers, data) {
    buffers.push(new Buffer('i' + data.toString(10) + 'e'))
  },
  decode: function () {
    var end = this.find(0x65)
    var number = this.data.toString('ascii', this.position + 1, end)
    this.position += end + 1 - this.position
    return new BigNumber(number, 10)
  }
})

// Profit
var value = new BigNumber('1234567890123456789', 10)
var encoded = bignumBencode.encode(value)
var decoded = bignumBencode.decode(encoded)

assert.deepEqual( value, decoded )
```

It has added some complexity, but the benchmarks surprisingly still show pretty much the same numbers, if not even better ones. I still need to add tests for this though.
What do you think?

**Comment by themasch** [comment]
"Branch protection options saved"

**Pull request merged**
